name: CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar validação com ESLint
        run: |
          npm install eslint --save-dev
          npx eslint script.js || true

      - name: Deploy no GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "kaiquechaves@cest.edu.br"
          git config --global user.name "KaiqCH"
          npm install --save-dev gh-pages
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}